#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port1,           rightmotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          leftmotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// global defintions
#define WAIT 100
#define HALT 32

// utility functions
void MoveForward()
{
	playSound(soundBlip);
	motor[leftmotor] = 60;
	motor[rightmotor] = -60;
	wait1Msec(WAIT);
}

void MoveBackward()
{
	playSound(soundException);
	motor[leftmotor] = -60;
	motor[rightmotor] = 60;
	wait1Msec(WAIT);
}

void TurnLeft()
{
	playSound(soundBeepBeep);
	motor[leftmotor] = 45;
	motor[rightmotor] = 45;
	wait1Msec(WAIT);
}

void TurnRight()
{
	playSound(soundBeepBeep);
	motor[leftmotor] = -45;
	motor[rightmotor] = -45;
	wait1Msec(WAIT);
}

void Halt()
{
	motor[leftmotor] = 0;
	motor[rightmotor] = 0;
	wait1Msec(HALT);
}

task main()
{
	int recvChar;

	while(true)
		{
		recvChar = getChar(UART1);

		//writeDebugStream("Received %d\n", recvChar);

		// 0 -> 48
		// 1 -> 49 -> L
		// 2 -> 50 -> R
		// 3 -> 51 -> F
		// 4 -> 52 -> B
		switch(recvChar)
		{
			// left
			case 49:
			{
				writeDebugStream("Pacman -> Turn Left!\n");
				TurnLeft();
			}
			break;

			// right
			case 50:
			{
				writeDebugStream("Pacman -> Turn right!\n");
				TurnRight();
			}
			break;

			// forward
			case 51:
			{
				writeDebugStream("Pacman -> Go forward!\n");
				MoveForward();
			}
			break;

			// backward
			case 52:
			{
				writeDebugStream("Pacman -> Go backward !\n");
				MoveBackward();
			}
			break;

			// halt
			default:
			{
				writeDebugStream("Pacman -> Stay!\n");
				Halt();
			}
			break;
		}
	}
}
